### PR TITLE
Fix issue 101

### LINKED ISSUE #101: OSX: Undefined symbols for architecture x86_64 __d_osx_image_init2
I followed the instructions given on https://github.com/ldc-developers/ldc/wiki/Installation with a few modifications to make the build successful on OSX (see below for required modifications):

when compiling + linking a hello world program main.d I get the following link error:

ldc2 main.d  
Undefined symbols for architecture x86_64:
  "__d_osx_image_init2", referenced from:
      _main in libphobos-ldc.a(dmain2.o)
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
Error: linking failed:
status: 1

***********************************\* installation *************************
sudo port install libconfig-hr (install libconfig)
then in ccmake, change llvm path to /opt/local/bin/llvm-config-mp-3.0 (to make it work with the macports version)

ccmake complains (" libconfig++ not found") ("consider manually setting the LIBCONFIG_CXXFLAGS and LIBCONFIG_LDFLAGS"). Unfortunately the instructions given here (http://www.dsource.org/projects/ldc/wiki/OSXBuildInstructions : you also need to set LIBCONFIG_LDFLAGS="-L/usr/local/lib -lconfig++" in advanced options of ccmake (while configuring, press 't', scroll down) didn't work as LIBCONFIG_LDFLAGS doesn't appear in advanced options.

but the following manual way works:
cmake .. -DLIBCONFIG_LDFLAGS="-L/opt/local/lib/ -lconfig++" -DLIBCONFIG_CXXFLAGS=-I/opt/local/include/
followed by make && make install

that compiles fine, ldc2 is created

### PR DESCRIPTION
**Pull request by dansanduleac**
Fix [Issue 101](https://github.com/ldc-developers/ldc/issues/101). Now compiles, threads work on OSX Lion 10.7.4, 64-bit, compiled from ldc-developers/ldc:master.

Revert upstream "fix Issue 4854 - Regression(2.047, Mac 10.5 only) writefln Segmentation fault if no globals", which was only intended for DMD/druntime.
As noted in the conflict, some changes have remained in `thread.d`, but ldc-developers/druntime@fe5ba38abff4c6b787f75b776ea9612e1c6780fc makes them inactive in LDC. It might be better to undo both of them completely.

This reverts commit 73cf2c150665cb17d9365a6e3d6cf144d76312d6.

Conflicts:

```
src/core/thread.d : kept Walter's changes but only if OsxManualTls
  maybe should remove those completely as they aren't needed for
  druntime-ldc.
```

### CODE REVIEW

**Comment by dnadlinger** [comment]
Thanks a lot for your work – unfortunately, I had already prepared a patch.

The reason I introduced `osxManualTls` was minimizing the source differences to the upstream version, which we generally try to do in order to make merges easier. If the code in thread.d diverges even further (which should hopefully _not_ be the case, considering druntime's design), just removing all the DMD-only code might be the cleaner solution indeed. As far as correctness of my commit is concerned, note that some of Walter's changes are actually to dead code (D-Programming-Language/druntime#238)…

**Comment by dansanduleac** [comment]
I get it now, yeah :) It does make sense to do that.
Thanks for pushing changes to make it work!
